Repository kubernetes-csi/livenessprobe, pull requests merged in 2020-08, with the labels that each got.

#76 Prepare 2.1 release
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-2.0.md
  CHANGELOG/CHANGELOG-2.1.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#77 Add rest of sig-storage chairs and tech-leads to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#79 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#78 Windows 2004 dockfile
  Dockerfile.Windows
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, sig/windows, size/XS

#81 Update changelog for 2.1
  CHANGELOG/CHANGELOG-2.1.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L
