Repository kubernetes-csi/livenessprobe, pull requests merged in 2020-10, with the labels that each got.

#83 Fix the failing multiarch builds
  Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#85 Revert to multiarch distroless base image
  Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#84 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#87 master: update release-tools
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#88 Make livenessprobe logging a little less verbose
  deployment/kubernetes/livenessprobe-sidecar.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note, size/XS
