Repository kubernetes-csi/livenessprobe, pull requests merged in 2024-05, with the labels that each got.

#262 Bump to Kubernetes 1.30
  .github/workflows/trivy.yaml
  cmd/livenessprobe/main.go
  go.mod
  go.sum
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/generate-patch-release-notes.sh
  release-tools/go-modules-targeted-update.sh
  release-tools/prow.sh
  release-tools/verify-logcheck.sh
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/rpc/common.go
  vendor/k8s.io/apimachinery/pkg/api/resource/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/runtime/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/runtime/helper.go
  vendor/k8s.io/apimachinery/pkg/runtime/schema/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/util/intstr/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/util/sets/doc.go
  vendor/k8s.io/apimachinery/pkg/util/sets/ordered.go
  vendor/k8s.io/apimachinery/pkg/util/sets/set.go
  vendor/k8s.io/apimachinery/pkg/util/validation/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/validation/validation.go
  vendor/k8s.io/component-base/featuregate/feature_gate.go
  vendor/k8s.io/component-base/logs/api/v1/kube_features.go
  vendor/k8s.io/component-base/logs/api/v1/options.go
  vendor/k8s.io/component-base/logs/api/v1/registry.go
  vendor/k8s.io/component-base/logs/api/v1/text.go
  vendor/k8s.io/component-base/logs/api/v1/types.go
  vendor/k8s.io/component-base/logs/api/v1/zz_generated.deepcopy.go
  vendor/k8s.io/klog/v2/internal/verbosity/verbosity.go
  vendor/k8s.io/klog/v2/textlogger/options.go
  vendor/k8s.io/klog/v2/textlogger/textlogger.go
  vendor/k8s.io/klog/v2/textlogger/textlogger_slog.go
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, approved, size/XXL, lgtm, release-note

#259 Support contextual logging
  Makefile
  cmd/livenessprobe/main.go
Labels: kind/feature, cncf-cla: yes, approved, lgtm, kind/cleanup, size/M, release-note, priority/important-longterm, wg/structured-logging

#266 Add changelog for v2.13
  CHANGELOG/CHANGELOG-2.13.md
Labels: cncf-cla: yes, approved, lgtm, size/M, kind/documentation, release-note-none
